#!/usr/bin/env bash
set -euo pipefail

# codeprism.dev VPS Setup Script
# Tested on: Ubuntu 24.04 (Hetzner CPX21 / CX23)
#
# Usage:
#   curl -sSL https://raw.githubusercontent.com/dan1d/codeprism/main/deploy/setup.sh | bash

CODEPRISM_REPO_URL="${CODEPRISM_REPO_URL:-https://github.com/dan1d/codeprism.git}"
APP_DIR="${APP_DIR:-/opt/codeprism}"
REPO_DIR="${REPO_DIR:-$APP_DIR/repo}"

echo "=== codeprism.dev VPS setup ==="

# 1. Install Docker (official method)
if ! command -v docker &>/dev/null; then
  echo "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  systemctl enable docker
  systemctl start docker
fi

# 2. Install Docker Compose plugin (if not bundled)
if ! docker compose version &>/dev/null; then
  echo "Installing Docker Compose..."
  apt-get update && apt-get install -y docker-compose-plugin
fi

# 3. Install git if missing (needed for clone)
if ! command -v git &>/dev/null; then
  echo "Installing git..."
  apt-get update && apt-get install -y git
fi

# 4. Create swap if none exists (prevents OOM kills during indexing)
if [ "$(swapon --show | wc -l)" -le 1 ]; then
  echo "Creating 4 GB swap..."
  fallocate -l 4G /swapfile && chmod 600 /swapfile
  mkswap /swapfile && swapon /swapfile
  echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

# 5. Configure firewall (UFW)
echo "Configuring firewall..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp    # SSH
ufw allow 80/tcp    # HTTP
ufw allow 443/tcp   # HTTPS
ufw allow 443/udp   # HTTP/3 (QUIC)
ufw --force enable

# 6. Create app directory
mkdir -p "$APP_DIR"

# 7. Clone or update repo
if [ -d "$APP_DIR/.git" ]; then
  REPO_DIR="$APP_DIR"
fi

mkdir -p "$(dirname -- "$REPO_DIR")"

if [ -d "$REPO_DIR/.git" ]; then
  echo "Updating codeprism..."
  cd "$REPO_DIR" && git pull --ff-only
else
  echo "Cloning codeprism..."
  git clone "$CODEPRISM_REPO_URL" "$REPO_DIR"
fi

# 8. Create .env with interactive prompts
ENV_FILE="$REPO_DIR/deploy/.env"
if [ ! -f "$ENV_FILE" ]; then
  echo ""
  echo "--- Configuration ---"

  # Domain
  read -rp "Your domain (e.g. codeprism.example.com) [codeprism.dev]: " DOMAIN
  DOMAIN="${DOMAIN:-codeprism.dev}"

  # Auto-generate admin key
  ADMIN_KEY=$(openssl rand -hex 32)

  # LLM provider + key
  echo ""
  echo "Supported LLM providers: gemini, anthropic, openai, deepseek"
  read -rp "LLM provider [gemini]: " LLM_PROVIDER
  LLM_PROVIDER="${LLM_PROVIDER:-gemini}"

  read -rsp "API key for $LLM_PROVIDER: " LLM_KEY
  echo ""

  # Map provider → env var name
  case "$LLM_PROVIDER" in
    anthropic) LLM_VAR="ANTHROPIC_API_KEY" ;;
    openai)    LLM_VAR="OPENAI_API_KEY" ;;
    deepseek)  LLM_VAR="DEEPSEEK_API_KEY" ;;
    *)         LLM_VAR="GOOGLE_API_KEY" ;;
  esac

  # Build env var values
  _GOOGLE_KEY=""; _ANTHROPIC_KEY=""; _OPENAI_KEY=""; _DEEPSEEK_KEY=""
  case "$LLM_VAR" in
    GOOGLE_API_KEY)    _GOOGLE_KEY="$LLM_KEY" ;;
    ANTHROPIC_API_KEY) _ANTHROPIC_KEY="$LLM_KEY" ;;
    OPENAI_API_KEY)    _OPENAI_KEY="$LLM_KEY" ;;
    DEEPSEEK_API_KEY)  _DEEPSEEK_KEY="$LLM_KEY" ;;
  esac

  cat > "$ENV_FILE" <<ENVEOF
# codeprism.dev configuration — generated by setup.sh
CODEPRISM_DOMAIN=${DOMAIN}
CODEPRISM_MULTI_TENANT=true
CODEPRISM_COMPANY_NAME=codeprism
CODEPRISM_ADMIN_KEY=${ADMIN_KEY}

# LLM keys (fill in the ones you use)
GOOGLE_API_KEY=${_GOOGLE_KEY}
ANTHROPIC_API_KEY=${_ANTHROPIC_KEY}
OPENAI_API_KEY=${_OPENAI_KEY}
DEEPSEEK_API_KEY=${_DEEPSEEK_KEY}

# CODEPRISM_TELEMETRY=true
# CF_API_TOKEN=  # Only needed for wildcard SSL with Cloudflare DNS
ENVEOF

  echo ""
  echo "Created $ENV_FILE"
  echo "Admin key (save this): $ADMIN_KEY"
fi

# 9. Build and start
cd "$REPO_DIR"
chmod +x ./deploy/update.sh ./deploy/backup.sh 2>/dev/null || true
./deploy/update.sh --build

echo ""
echo "=== codeprism.dev is running ==="
echo "Dashboard: https://$( grep CODEPRISM_DOMAIN "$REPO_DIR/deploy/.env" | head -1 | cut -d= -f2 )"
echo "MCP endpoint: https://$( grep CODEPRISM_DOMAIN "$REPO_DIR/deploy/.env" | head -1 | cut -d= -f2 )/mcp"
echo ""
echo "Next steps:"
echo "  1. Point your domain's A record to this server's IP"
echo "  2. Verify settings: $ENV_FILE"
echo "  3. Re-deploy after changes: cd $REPO_DIR && ./deploy/update.sh --build"
